---
title: "KNN"
author: "Youngwook Jung"
date: '2020 12 9 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##### Supervised learning; Alcohol consumption frequency analysis
### KNN

df_supervised = data.frame(mydata_c[,8], mydata_c[,2], mydata_c[,5], mydata_c[,6], mydata_c[,7], otu_sigPCAScores[,1:69])

colnames(df_supervised)[1] <- "alcohol_frequency"
colnames(df_supervised)[2] <- "age_cat"
colnames(df_supervised)[3] <- "weight_kg"
colnames(df_supervised)[4] <- "race"
colnames(df_supervised)[5] <- "sex"

df_supervised$alcohol_frequency <- as.factor(df_supervised$alcohol_frequency)
df_supervised$age_cat <- as.factor(df_supervised$age_cat)
df_supervised$weight_kg <- as.numeric(df_supervised$weight_kg)
df_supervised$race <- as.factor(df_supervised$race)
df_supervised$sex <- as.factor(df_supervised$sex)

library(caret)
library(class)
library(dplyr)
library(e1071)
library(FNN) 
library(gmodels) 
library(psych)
library(kknn)
set.seed(1)

trainid = sample(1:nrow(df_supervised), nrow(df_supervised)/2)
train = df_supervised[trainid, ]
test = df_supervised[-trainid, ]

knn.fit10 = kknn(factor(alcohol_frequency) ~., train=train, test=test, k = 10)
knn_10 <- data.frame(knn.fit10$fitted.values, test$alcohol_frequency)
mean(knn.fit10$fitted.values != test$alcohol_frequency)

err = rep(NA,50)
for (i in c(1:50)){
knn.fit = kknn(factor(alcohol_frequency) ~., train=train, test=test, k = i)
knn <- data.frame(knn.fit$fitted.values, test$alcohol_frequency)
err[i]= mean(knn.fit$fitted.values != test$alcohol_frequency)
}
aa <- data.frame(c(1:50),err)
colnames(aa)[1] <- "K"
colnames(aa)[2] <- "Misclassification error"

plot(aa$K, aa$`Misclassification error`, xlab="K", ylab="Misclassification error")
```
