---
title: "somGenerator"
author: "reuven"
date: "11/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, eval=FALSE}
# Only Run this to reload cleaneddata and save it to rds file
#
#cleanData = read.table(file = 'C:/Users/reuven/Documents/Classes/STAT542Project/data/clean.csv', sep = "\t")
#saveRDS(cleanData,file = "C:/Users/reuven/Documents/Classes/STAT542Project/data/cleanedData.rds")s
```

Run to load entire dataset
```{r, eval=FALSE}
setwd("C:/Users/reuven/Documents/Classes/STAT542Project")
cleanData = readRDS("C:/Users/reuven/Documents/Classes/STAT542Project/data/cleanedData.rds")
nonOtuInfo = cleanData[,1:9]
nonOtuInfo$bmi = as.numeric(nonOtuInfo$bmi)
nonOtuInfo$weight_kg = as.numeric(nonOtuInfo$weight_kg)
```


Create and save numeric OTU Info of cleanedData 
```{r}
otuInfo = cleanData[1:nrow(cleanData),c(10:ncol(cleanData))]
otuInfo[] = lapply(otuInfo,as.numeric)
nonOtuInfo = cleanData[,1:9]
nonOtuInfo$bmi = as.numeric(nonOtuInfo$bmi)
nonOtuInfo$weight_kg = as.numeric(nonOtuInfo$weight_kg)
saveRDS(otuInfo,"data/otuInfo.rds")
saveRDS(nonOtuInfo,"data/nonOtuInfo.rds")

```


```{r}


#library(princomp)
if (!exists("otuInfo")){
  otuInfo = readRDS('data/otuInfo.rds')
}
n = nrow(otuInfo)
m= ncol(otuInfo)

nonZero=colSums(otuInfo!=0)
nonZeroSorted = sort(nonZero,decreasing = TRUE)

nonZeroLimit = nonZeroSorted[8359]
print(nonZeroLimit) # Only 8 of them are nonzero
nonZeroSorted[8355:8365] #if we use above cutoff, we favor certain attributes with 8 nonzero but not others: Use 9 as cutoff

plot(nonZeroSorted[1:n]/n,lty=1,type="l",xlab="Sorted Attributes",ylab="Non-Zero element ratio")


#selectAttr= nonZero>8 #cutoff
#selectAttr= nonZero>.01*n #Accepting the 1876 most populated attributes
#selectOTUInfo = otuInfo[,selectAttr]
#if (!exists("otu.pca")){otu.pca = princomp(selectOTUInfo)}

#pcaLimit =sum((cumsum(otu.pca$sdev^2)/sum(otu.pca$sdev^2))<=.85)

#otu.sigPCAScores = otu.pca$scores[,1:pcaLimit]

if (!exists("otu_sigPCAScores")){
  otu.sigPCAScores = readRDS('data/otu_sigPCAScores.rds')
}

pairs(otu.sigPCAScores[,1:6])
#saveRDS(otu.sigPCAScores,"data/otu_sigPCAScores.rds")
```
```{r}

score1 = scores[,1]
score2 = scores[,2]
score3 = scores[,3]
score4 = scores[,4]
df = data.frame(PC1 = score1,PC2 = score2, PC3 = score3, PC4 = score4)
df12 = data.frame(PCA1 = score1,PCA2 = score2)
df13 = data.frame(x = score1,y = score3)
df23 = data.frame(x = score2,y = score3)
df14 = data.frame(x = score1,y = score4)
df24 = data.frame(x = score2,y = score4)
df32 = data.frame(x = score3,y = score4)


g12 <- ggplot(df, aes(x=PC1, y=PC2) ) +
  geom_bin2d(bins = 60) +
  scale_fill_continuous(type = "viridis") +
  theme_bw()

g13 <- ggplot(df, aes(x=PC1, y=PC3) ) +
  geom_bin2d(bins = 60) +
  scale_fill_continuous(type = "viridis") +
  theme_bw()

g23 <- ggplot(df, aes(x=PC2, y=PC3) ) +
  scale_fill_continuous(type = "viridis") +
  geom_bin2d(bins = 60) +
  theme_bw()

g14 <- ggplot(df, aes(x=PC1, y=PC4) ) +
  scale_fill_continuous(type = "viridis") +
  geom_bin2d(bins = 60) +
  theme_bw()

g24 <- ggplot(df, aes(x=PC2, y=PC4) ) +
  scale_fill_continuous(type = "viridis") +
  geom_bin2d(bins = 60) +
  theme_bw()

g34 <- ggplot(df, aes(x=PC2, y=PC4) ) +
  scale_fill_continuous(type = "viridis") +
  geom_bin2d(bins = 60) +
  theme_bw()

ggarrange(g12,g13,g23,g14,ncol = 2,nrow=2)

ggarrange(g12,g13,g23,g14,g24,g34, ncol = 3,nrow=2)
```


```{r}
library(kohonen)
library(ggplot2)
if (!exists("otu.sigPCAScores")){otu.pca = readRDS('data/otu_sigPCAScores.rds')}

otu.somLarge =som(otu.sigPCAScores,grid = somgrid(21,21,"hexagonal"))
plot(otu.somLarge,type="dist.neighbours")
plot(otu.somLarge,type="counts")
```

```{r}
K = 3:7
labels = data.frame(matrix(,nrow=8359,ncol=5))
names(labels) = apply(as.matrix(K),1,toString)


for (k in K){
  currOTU.som = som(otu.sigPCAScores,grid = somgrid(k,1,"rectangular"))
  labels[toString(k)] <- currOTU.som$unit.classif
}
#saveRDS(labels,"data/som_lables.rds")


occurMatrix = matrix(,nrow=7,ncol=5)
for (kInd in 1:5){
  for (l in 1:7){
    occurMatrix[l,kInd] = (sum(labels[toString(K[kInd])]==l))
  }
}
occurancesK = data.frame(occurMatrix)
names(occurancesK) = names(labels)
rownames(occurancesK) = apply(as.matrix(1:7),1,toString)
occurancesK
```


```{r}

pairs(otu.sigPCAScores[,1:6],col=c("red","blue","green")[as.matrix(labels["3"])])
pairs(otu.sigPCAScores[,1:6],col=c("red","blue","green","yellow","black")[as.matrix(labels["5"])])
pairs(otu.sigPCAScores[,1:6],col=c("red","blue","green","yellow","black","purple","cyan")[as.matrix(labels["7"])])

```

